version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PYTHON_API_URL=http://python-backend:5001
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    depends_on:
      - python-backend
    env_file:
      - .env

  python-backend:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5001:5001"
    volumes:
      - ./personal.py:/app/personal.py
      - ./app.py:/app/app.py
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_PORT=5001
      - VERIFY_SSL=false
    env_file:
      - .env 